#!/usr/bin/env python
"""Configure local Google login without printing OAuth secrets.

This helper reads a downloaded Google web OAuth client file, validates that the
local callback is authorized, and writes an ignored backend/.env suitable for
local authentication testing.
"""
from __future__ import annotations

import argparse
import json
import secrets
from pathlib import Path

from cryptography.fernet import Fernet


BACKEND_DIR = Path(__file__).resolve().parents[1]
DEFAULT_REDIRECT_URI = "http://localhost:8000/api/auth/google/callback"


def load_google_web_client(path: Path) -> dict:
    raw = path.read_text(encoding="utf-8-sig").strip()
    # Some browser/download flows prepend a harmless label to the JSON payload.
    if raw.startswith("user{"):
        raw = raw[4:]
    payload = json.loads(raw)
    client = payload.get("web")
    if not isinstance(client, dict):
        raise ValueError("Google credential must be a Web application OAuth client.")
    if not client.get("client_id") or not client.get("client_secret"):
        raise ValueError("Google credential is missing client_id or client_secret.")
    return client


def render_env(client: dict, redirect_uri: str) -> str:
    app_secret = secrets.token_urlsafe(48)
    encryption_key = Fernet.generate_key().decode("ascii")
    return f"""# Local configuration generated by scripts/configure_local_google_auth.py
# This file is gitignored. Do not commit or share it.
APP_ENV=local

BACKEND_HOST=0.0.0.0
BACKEND_PORT=8000
BACKEND_PUBLIC_BASE_URL=http://localhost:8000
FRONTEND_ORIGIN=http://localhost:5173
FRONTEND_URL=http://localhost:5173

# Any verified Google account may log in. No account is granted admin access.
AUTH_REQUIRED=true
GOOGLE_CLIENT_ID={client["client_id"]}
GOOGLE_CLIENT_SECRET={client["client_secret"]}
GOOGLE_REDIRECT_URI={redirect_uri}
ADMIN_EMAILS=

# Local auth/session database. Replace with Neon DATABASE_URL for production.
DATABASE_URL=sqlite:///./auth_local.db

APP_SECRET_KEY={app_secret}
SESSION_TOKEN_SECRET={app_secret}
SESSION_TOKEN_TTL_SECONDS=43200
CREDENTIAL_ENCRYPTION_KEY={encryption_key}
TOKEN_ENCRYPTION_KEY={encryption_key}
CREDENTIAL_VAULT_BACKEND=db

SESSION_COOKIE_SECURE=false
SESSION_COOKIE_SAMESITE=lax
SESSION_COOKIE_DOMAIN=

# Safe local trading defaults.
DHAN_MODE=MOCK
DHAN_READ_ONLY_REAL_DATA=true
PAPER_MODE_ENABLED=true
ENABLE_LIVE_ORDERS=false
WEBHOOK_TRADING_ENABLED=false
WEBHOOK_HMAC_REQUIRED=true
REQUIRE_MARKET_HOURS=false

AUTO_RESOLVE_SECURITY_ID=true
DHAN_SCRIP_MASTER_PATH=data/dhan_scrip_master.csv
ALLOW_DEFAULT_SECURITY_ID=false
DEFAULT_SECURITY_ID=
RUNTIME_STATE_DIR=runtime_state
RUNTIME_LOG_DIR=runtime_logs
DEBUG_ENABLED=false
MARKET_CLOSED_DEBUG=false
FORCE_ALLOW_ORDER_WHEN_MARKET_CLOSED=false
WEBHOOK_RATE_LIMIT_PER_MINUTE=120
DHAN_API_MAX_REQUESTS_PER_SECOND=4
DHAN_API_BURST=4
DHAN_API_MAX_RETRY_AFTER_SECONDS=60
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("credential_file", type=Path)
    parser.add_argument("--redirect-uri", default=DEFAULT_REDIRECT_URI)
    args = parser.parse_args()

    client = load_google_web_client(args.credential_file.resolve())
    redirect_uris = set(client.get("redirect_uris") or [])
    if args.redirect_uri not in redirect_uris:
        raise SystemExit(
            f"Google OAuth client does not authorize callback: {args.redirect_uri}"
        )

    env_path = BACKEND_DIR / ".env"
    env_path.write_text(render_env(client, args.redirect_uri), encoding="utf-8")
    print("Configured backend/.env for local Google authentication.")
    print("Login policy: any verified Google account; no admin accounts.")
    print(f"Redirect URI: {args.redirect_uri}")
    print("Database: local ignored SQLite (auth_local.db)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
